<div class="deco-shipping-wrapper" >
    <div class="tittle-text-wrapper">
        <div class="text">
            Calcule o preço e o prazo de entrega estimados para este produto.
        </div>
    </div>
    <div class="elements-wrapper">
        <span>CEP</span>
        <input id="deco-shipping-cep" type="number"/>
        <button id="deco-shipping-getrate">Calcular</button>
    </div>
    <div class="error-message"></div>
    <div id="deco-shipping-table" ></div>
    <div id="loading-overlay">
        <div class="loader"></div>
        <span class="loading-text">Carregando...</span>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "estimateRate":  {}
        }
    }
</script>